linters:
  enable-all: true
  disable:
    - exportloopref
    - wsl
    - depguard
    - gochecknoglobals
    - revive
    - err113
    - exhaustive
    - errorlint
    - nlreturn
    - nonamedreturns
    - wrapcheck

linters-settings:
  interfacebloat:
    max: 16

  varnamelen:
    max-distance: 32

issues:
  exclude:
    - ST1001
    - ST1003
    - ST1023
